/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vues;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author btssio
 */
public class VueMedicament extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMedicament
     */
    public VueMedicament() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMedicament = new javax.swing.JPanel();
        jLabelMedicament = new javax.swing.JLabel();
        jLabelCode = new javax.swing.JLabel();
        jLabelNomCommercial = new javax.swing.JLabel();
        jLabelFamille = new javax.swing.JLabel();
        jLabelComposition = new javax.swing.JLabel();
        jLabelEffetIndesirables = new javax.swing.JLabel();
        jLabelContreIndications = new javax.swing.JLabel();
        jLabelPrixEchantillon = new javax.swing.JLabel();
        jButtonPrecedent = new javax.swing.JButton();
        jButtonSuivant = new javax.swing.JButton();
        jButtonQuitter = new javax.swing.JButton();
        jTextFieldCode = new javax.swing.JTextField();
        jTextFieldNomCommercial = new javax.swing.JTextField();
        jComboBoxFamille = new javax.swing.JComboBox();
        jScrollPaneContreIndications = new javax.swing.JScrollPane();
        jTextAreaContreIndications = new javax.swing.JTextArea();
        jScrollPaneEffetsIndesirables = new javax.swing.JScrollPane();
        jTextAreaEffetsIndesirables = new javax.swing.JTextArea();
        jTextFieldPrixEchantillon = new javax.swing.JTextField();
        jTextFieldComposition = new javax.swing.JTextField();
        jButtonMenuGeneral = new javax.swing.JButton();
        jTextFieldRechercher = new javax.swing.JTextField();
        jLabelRechercher = new javax.swing.JLabel();
        jLabelChercher = new javax.swing.JLabel();
        jComboBoxChercher = new javax.swing.JComboBox();
        jButtonOk = new javax.swing.JButton();
        jSeparator = new javax.swing.JSeparator();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Médicament");
        setResizable(false);

        jPanelMedicament.setLayout(null);

        jLabelMedicament.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabelMedicament.setForeground(new java.awt.Color(0, 0, 153));
        jLabelMedicament.setText("Médicament");
        jPanelMedicament.add(jLabelMedicament);
        jLabelMedicament.setBounds(220, 0, 235, 44);

        jLabelCode.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCode.setForeground(new java.awt.Color(0, 0, 153));
        jLabelCode.setText("Code");
        jPanelMedicament.add(jLabelCode);
        jLabelCode.setBounds(150, 120, 50, 20);

        jLabelNomCommercial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNomCommercial.setForeground(new java.awt.Color(0, 0, 153));
        jLabelNomCommercial.setText("Nom commercial");
        jPanelMedicament.add(jLabelNomCommercial);
        jLabelNomCommercial.setBounds(150, 150, 100, 14);

        jLabelFamille.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelFamille.setForeground(new java.awt.Color(0, 0, 153));
        jLabelFamille.setText("Famille");
        jPanelMedicament.add(jLabelFamille);
        jLabelFamille.setBounds(150, 180, 60, 14);

        jLabelComposition.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelComposition.setForeground(new java.awt.Color(0, 0, 153));
        jLabelComposition.setText("Composition");
        jPanelMedicament.add(jLabelComposition);
        jLabelComposition.setBounds(150, 210, 80, 14);

        jLabelEffetIndesirables.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelEffetIndesirables.setForeground(new java.awt.Color(0, 0, 153));
        jLabelEffetIndesirables.setText("Effets indésirables");
        jPanelMedicament.add(jLabelEffetIndesirables);
        jLabelEffetIndesirables.setBounds(150, 270, 110, 14);

        jLabelContreIndications.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelContreIndications.setForeground(new java.awt.Color(0, 0, 153));
        jLabelContreIndications.setText("Contre indications");
        jPanelMedicament.add(jLabelContreIndications);
        jLabelContreIndications.setBounds(150, 350, 110, 14);

        jLabelPrixEchantillon.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPrixEchantillon.setForeground(new java.awt.Color(0, 0, 153));
        jLabelPrixEchantillon.setText("Prix échantillon");
        jPanelMedicament.add(jLabelPrixEchantillon);
        jLabelPrixEchantillon.setBounds(150, 410, 100, 14);

        jButtonPrecedent.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonPrecedent.setForeground(new java.awt.Color(0, 0, 153));
        jButtonPrecedent.setText("Précédent");
        jPanelMedicament.add(jButtonPrecedent);
        jButtonPrecedent.setBounds(150, 450, 100, 23);

        jButtonSuivant.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonSuivant.setForeground(new java.awt.Color(0, 0, 153));
        jButtonSuivant.setText("Suivant");
        jPanelMedicament.add(jButtonSuivant);
        jButtonSuivant.setBounds(290, 450, 90, 23);

        jButtonQuitter.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonQuitter.setForeground(new java.awt.Color(0, 0, 153));
        jButtonQuitter.setText("Quitter");
        jPanelMedicament.add(jButtonQuitter);
        jButtonQuitter.setBounds(590, 450, 90, 23);
        jPanelMedicament.add(jTextFieldCode);
        jTextFieldCode.setBounds(260, 120, 190, 20);
        jPanelMedicament.add(jTextFieldNomCommercial);
        jTextFieldNomCommercial.setBounds(260, 150, 190, 20);

        jComboBoxFamille.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelMedicament.add(jComboBoxFamille);
        jComboBoxFamille.setBounds(260, 180, 190, 20);

        jTextAreaContreIndications.setColumns(20);
        jTextAreaContreIndications.setLineWrap(true);
        jTextAreaContreIndications.setRows(5);
        jScrollPaneContreIndications.setViewportView(jTextAreaContreIndications);

        jPanelMedicament.add(jScrollPaneContreIndications);
        jScrollPaneContreIndications.setBounds(260, 330, 430, 80);

        jTextAreaEffetsIndesirables.setColumns(20);
        jTextAreaEffetsIndesirables.setLineWrap(true);
        jTextAreaEffetsIndesirables.setRows(5);
        jScrollPaneEffetsIndesirables.setViewportView(jTextAreaEffetsIndesirables);

        jPanelMedicament.add(jScrollPaneEffetsIndesirables);
        jScrollPaneEffetsIndesirables.setBounds(260, 240, 430, 70);
        jPanelMedicament.add(jTextFieldPrixEchantillon);
        jTextFieldPrixEchantillon.setBounds(260, 410, 88, 20);
        jPanelMedicament.add(jTextFieldComposition);
        jTextFieldComposition.setBounds(260, 210, 190, 20);

        jButtonMenuGeneral.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonMenuGeneral.setForeground(new java.awt.Color(0, 0, 153));
        jButtonMenuGeneral.setText("Menu général");
        jPanelMedicament.add(jButtonMenuGeneral);
        jButtonMenuGeneral.setBounds(10, 10, 130, 40);

        jTextFieldRechercher.setText("Nom commerical");
        jTextFieldRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRechercherActionPerformed(evt);
            }
        });
        jPanelMedicament.add(jTextFieldRechercher);
        jTextFieldRechercher.setBounds(260, 50, 190, 20);

        jLabelRechercher.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelRechercher.setForeground(new java.awt.Color(0, 0, 153));
        jLabelRechercher.setText("Rechercher");
        jPanelMedicament.add(jLabelRechercher);
        jLabelRechercher.setBounds(150, 50, 70, 14);

        jLabelChercher.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelChercher.setForeground(new java.awt.Color(0, 0, 153));
        jLabelChercher.setText("Chercher");
        jPanelMedicament.add(jLabelChercher);
        jLabelChercher.setBounds(150, 80, 70, 14);

        jComboBoxChercher.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelMedicament.add(jComboBoxChercher);
        jComboBoxChercher.setBounds(260, 80, 190, 20);

        jButtonOk.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonOk.setForeground(new java.awt.Color(0, 0, 153));
        jButtonOk.setText("OK");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });
        jPanelMedicament.add(jButtonOk);
        jButtonOk.setBounds(460, 80, 80, 23);

        jSeparator.setBackground(new java.awt.Color(0, 0, 153));
        jSeparator.setForeground(new java.awt.Color(0, 0, 153));
        jPanelMedicament.add(jSeparator);
        jSeparator.setBounds(100, 110, 540, 20);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gsb_background.png"))); // NOI18N
        jPanelMedicament.add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 700, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMedicament, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMedicament, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jTextFieldRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRechercherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRechercherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueMedicament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueMedicament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueMedicament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueMedicament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueMedicament().setVisible(true);
            }
        });
    }

    /**
     *
     * @return
     */
    public JButton getjButtonPrecedent() {
        return jButtonPrecedent;
    }

    /**
     *
     * @return
     */
    public JButton getjButtonQuitter() {
        return jButtonQuitter;
    }

    /**
     *
     * @return
     */
    public JLabel getjLabelChercher() {
        return jLabelChercher;
    }

    /**
     *
     * @return
     */
    public JLabel getjLabelRechercher() {
        return jLabelRechercher;
    }

    /**
     *
     * @return
     */
    public JButton getjButtonSuivant() {
        return jButtonSuivant;
    }

    /**
     *
     * @return
     */
    public JComboBox getjComboBoxFamille() {
        return jComboBoxFamille;
    }

    /**
     *
     * @return
     */
    public JTextArea getjTextAreaContreIndications() {
        return jTextAreaContreIndications;
    }

    /**
     *
     * @return
     */
    public JTextArea getjTextAreaEffetsIndesirables() {
        return jTextAreaEffetsIndesirables;
    }

    /**
     *
     * @return
     */
    public JTextField getjTextFieldCode() {
        return jTextFieldCode;
    }

    /**
     *
     * @return
     */
    public JTextField getjTextFieldComposition() {
        return jTextFieldComposition;
    }

    /**
     *
     * @return
     */
    public JTextField getjTextFieldNomCommercial() {
        return jTextFieldNomCommercial;
    }

    /**
     *
     * @return
     */
    public JTextField getjTextFieldPrixEchantillon() {
        return jTextFieldPrixEchantillon;
    }

    /**
     *
     * @return
     */
    public JButton getjButtonMenuGeneral() {
        return jButtonMenuGeneral;
    }

    /**
     *
     * @return
     */
    public JButton getjButtonOk() {
        return jButtonOk;
    }

    /**
     *
     * @return
     */
    public JComboBox getjComboBoxChercher() {
        return jComboBoxChercher;
    }

    /**
     *
     * @return
     */
    public JTextField getjTextFieldRechercher() {
        return jTextFieldRechercher;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMenuGeneral;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JButton jButtonPrecedent;
    private javax.swing.JButton jButtonQuitter;
    private javax.swing.JButton jButtonSuivant;
    private javax.swing.JComboBox jComboBoxChercher;
    private javax.swing.JComboBox jComboBoxFamille;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelChercher;
    private javax.swing.JLabel jLabelCode;
    private javax.swing.JLabel jLabelComposition;
    private javax.swing.JLabel jLabelContreIndications;
    private javax.swing.JLabel jLabelEffetIndesirables;
    private javax.swing.JLabel jLabelFamille;
    private javax.swing.JLabel jLabelMedicament;
    private javax.swing.JLabel jLabelNomCommercial;
    private javax.swing.JLabel jLabelPrixEchantillon;
    private javax.swing.JLabel jLabelRechercher;
    private javax.swing.JPanel jPanelMedicament;
    private javax.swing.JScrollPane jScrollPaneContreIndications;
    private javax.swing.JScrollPane jScrollPaneEffetsIndesirables;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JTextArea jTextAreaContreIndications;
    private javax.swing.JTextArea jTextAreaEffetsIndesirables;
    private javax.swing.JTextField jTextFieldCode;
    private javax.swing.JTextField jTextFieldComposition;
    private javax.swing.JTextField jTextFieldNomCommercial;
    private javax.swing.JTextField jTextFieldPrixEchantillon;
    private javax.swing.JTextField jTextFieldRechercher;
    // End of variables declaration//GEN-END:variables
}
