/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vues;

import javax.swing.JCheckBox;

/**
 *
 * @author pnoel
 */
public class VueMenuGeneral extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMenuGeneral
     */
    public VueMenuGeneral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenuGeneral = new javax.swing.JPanel();
        jLabelMenuGeneral = new javax.swing.JLabel();
        jCheckBoxComptesRendus = new javax.swing.JCheckBox();
        jCheckBoxVisiteurs = new javax.swing.JCheckBox();
        jCheckBoxPraticiens = new javax.swing.JCheckBox();
        jCheckBoxMedicaments = new javax.swing.JCheckBox();
        jCheckBoxQuitter = new javax.swing.JCheckBox();
        jCheckBoxDeconnection = new javax.swing.JCheckBox();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Gestion des comptes rendus");
        setResizable(false);

        jPanelMenuGeneral.setLayout(null);

        jLabelMenuGeneral.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabelMenuGeneral.setForeground(new java.awt.Color(0, 0, 153));
        jLabelMenuGeneral.setText("Gestion des comptes rendus");
        jPanelMenuGeneral.add(jLabelMenuGeneral);
        jLabelMenuGeneral.setBounds(40, 60, 530, 44);

        jCheckBoxComptesRendus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxComptesRendus.setForeground(new java.awt.Color(0, 0, 153));
        jCheckBoxComptesRendus.setText("Comptes-Rendus");
        jPanelMenuGeneral.add(jCheckBoxComptesRendus);
        jCheckBoxComptesRendus.setBounds(220, 160, 130, 23);

        jCheckBoxVisiteurs.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxVisiteurs.setForeground(new java.awt.Color(0, 0, 153));
        jCheckBoxVisiteurs.setText("Visiteurs");
        jPanelMenuGeneral.add(jCheckBoxVisiteurs);
        jCheckBoxVisiteurs.setBounds(220, 200, 90, 23);

        jCheckBoxPraticiens.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxPraticiens.setForeground(new java.awt.Color(0, 0, 153));
        jCheckBoxPraticiens.setText("Praticiens");
        jCheckBoxPraticiens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPraticiensActionPerformed(evt);
            }
        });
        jPanelMenuGeneral.add(jCheckBoxPraticiens);
        jCheckBoxPraticiens.setBounds(220, 240, 100, 23);

        jCheckBoxMedicaments.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxMedicaments.setForeground(new java.awt.Color(0, 0, 153));
        jCheckBoxMedicaments.setText("Médicaments");
        jPanelMenuGeneral.add(jCheckBoxMedicaments);
        jCheckBoxMedicaments.setBounds(220, 280, 110, 23);

        jCheckBoxQuitter.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxQuitter.setForeground(new java.awt.Color(0, 0, 153));
        jCheckBoxQuitter.setText("Quitter");
        jPanelMenuGeneral.add(jCheckBoxQuitter);
        jCheckBoxQuitter.setBounds(220, 360, 90, 23);

        jCheckBoxDeconnection.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxDeconnection.setForeground(new java.awt.Color(0, 0, 153));
        jCheckBoxDeconnection.setText("Déconnection");
        jPanelMenuGeneral.add(jCheckBoxDeconnection);
        jCheckBoxDeconnection.setBounds(220, 320, 110, 23);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gsb_background.png"))); // NOI18N
        jPanelMenuGeneral.add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 740, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenuGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenuGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxPraticiensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPraticiensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxPraticiensActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueMenuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueMenuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueMenuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueMenuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueMenuGeneral().setVisible(true);
            }
        });
    }
    
    /**
     *
     * @return
     */
    public JCheckBox getjCheckBoxComptesRendus() {
        return jCheckBoxComptesRendus;
    }

    /**
     *
     * @return
     */
    public JCheckBox getjCheckBoxMedicaments() {
        return jCheckBoxMedicaments;
    }
    
    /**
     *
     * @return
     */
    public JCheckBox getjCheckBoxPraticiens() {
        return jCheckBoxPraticiens;
    }
    
    /**
     *
     * @return
     */
    public JCheckBox getjCheckBoxVisiteurs() {
        return jCheckBoxVisiteurs;
    }
    
    /**
     *
     * @return
     */
    public JCheckBox getjCheckBoxQuitter() {
        return jCheckBoxQuitter;
    }

    /**
     *
     * @return
     */
    public JCheckBox getjCheckBoxDeconnection() {
        return jCheckBoxDeconnection;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxComptesRendus;
    private javax.swing.JCheckBox jCheckBoxDeconnection;
    private javax.swing.JCheckBox jCheckBoxMedicaments;
    private javax.swing.JCheckBox jCheckBoxPraticiens;
    private javax.swing.JCheckBox jCheckBoxQuitter;
    private javax.swing.JCheckBox jCheckBoxVisiteurs;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelMenuGeneral;
    private javax.swing.JPanel jPanelMenuGeneral;
    // End of variables declaration//GEN-END:variables
}
