/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vues;

import javax.swing.JCheckBox;

/**
 *
 * @author btssio
 */
public class VueMenuGeneral extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMenuGeneral
     */
    public VueMenuGeneral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCheckBoxComptesRendus = new javax.swing.JCheckBox();
        jCheckBoxVisiteurs = new javax.swing.JCheckBox();
        jCheckBoxPracticiens = new javax.swing.JCheckBox();
        jCheckBoxMedicaments = new javax.swing.JCheckBox();
        jCheckBoxQuitter = new javax.swing.JCheckBox();
        jCheckBoxDeconnection = new javax.swing.JCheckBox();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion des comptes rendus");
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Gestion des comptes rendus");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 60, 530, 44);

        jCheckBoxComptesRendus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxComptesRendus.setForeground(new java.awt.Color(0, 0, 153));
        jCheckBoxComptesRendus.setText("Comptes-Rendus");
        jPanel1.add(jCheckBoxComptesRendus);
        jCheckBoxComptesRendus.setBounds(220, 160, 130, 23);

        jCheckBoxVisiteurs.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxVisiteurs.setForeground(new java.awt.Color(0, 0, 153));
        jCheckBoxVisiteurs.setText("Visiteurs");
        jPanel1.add(jCheckBoxVisiteurs);
        jCheckBoxVisiteurs.setBounds(220, 200, 90, 23);

        jCheckBoxPracticiens.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxPracticiens.setForeground(new java.awt.Color(0, 0, 153));
        jCheckBoxPracticiens.setText("Practiciens");
        jPanel1.add(jCheckBoxPracticiens);
        jCheckBoxPracticiens.setBounds(220, 240, 100, 23);

        jCheckBoxMedicaments.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxMedicaments.setForeground(new java.awt.Color(0, 0, 153));
        jCheckBoxMedicaments.setText("Médicaments");
        jPanel1.add(jCheckBoxMedicaments);
        jCheckBoxMedicaments.setBounds(220, 280, 110, 23);

        jCheckBoxQuitter.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxQuitter.setForeground(new java.awt.Color(0, 0, 153));
        jCheckBoxQuitter.setText("Quitter");
        jPanel1.add(jCheckBoxQuitter);
        jCheckBoxQuitter.setBounds(220, 360, 90, 23);

        jCheckBoxDeconnection.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxDeconnection.setForeground(new java.awt.Color(0, 0, 153));
        jCheckBoxDeconnection.setText("Déconnection");
        jPanel1.add(jCheckBoxDeconnection);
        jCheckBoxDeconnection.setBounds(220, 320, 110, 23);

        jLabelBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\Benoit\\Pictures\\gsb_background.png")); // NOI18N
        jPanel1.add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 740, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VueMenuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VueMenuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VueMenuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VueMenuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VueMenuGeneral().setVisible(true);
//            }
//        });
//    }
    public JCheckBox getjCheckBoxComptesRendus() {
        return jCheckBoxComptesRendus;
    }

    public JCheckBox getjCheckBoxMedicaments() {
        return jCheckBoxMedicaments;
    }
    
    public JCheckBox getjCheckBoxPracticiens() {
        return jCheckBoxPracticiens;
    }
    
    public JCheckBox getjCheckBoxVisiteurs() {
        return jCheckBoxVisiteurs;
    }
    
    public JCheckBox getjCheckBoxQuitter() {
        return jCheckBoxQuitter;
    }

    public JCheckBox getjCheckBoxDeconnection() {
        return jCheckBoxDeconnection;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxComptesRendus;
    private javax.swing.JCheckBox jCheckBoxDeconnection;
    private javax.swing.JCheckBox jCheckBoxMedicaments;
    private javax.swing.JCheckBox jCheckBoxPracticiens;
    private javax.swing.JCheckBox jCheckBoxQuitter;
    private javax.swing.JCheckBox jCheckBoxVisiteurs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
