/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vues;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author btssio
 */
public class VuePraticien extends javax.swing.JFrame {

    /**
     * Creates new form JFrameVisiteur
     */
    public VuePraticien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPraticien = new javax.swing.JPanel();
        jComboBoxChercher = new javax.swing.JComboBox();
        jTextFieldCoefNotoriete = new javax.swing.JTextField();
        jButtonSuivant = new javax.swing.JButton();
        jButtonPrecedent = new javax.swing.JButton();
        jButtonQuitter = new javax.swing.JButton();
        jButtonOk = new javax.swing.JButton();
        jSeparator = new javax.swing.JSeparator();
        jLabelNom = new javax.swing.JLabel();
        jLabelPrenom = new javax.swing.JLabel();
        jLabelPracticien = new javax.swing.JLabel();
        jLabelChercher = new javax.swing.JLabel();
        jLabelAdresse = new javax.swing.JLabel();
        jLabelVille = new javax.swing.JLabel();
        jLabelSecteur = new javax.swing.JLabel();
        jLabelLieuExercice = new javax.swing.JLabel();
        jComboBoxLieuExercice = new javax.swing.JComboBox();
        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldPrenom = new javax.swing.JTextField();
        jTextFieldAdresse = new javax.swing.JTextField();
        jTextFieldCodePostal = new javax.swing.JTextField();
        jTextFieldVille = new javax.swing.JTextField();
        jLabelRechercher = new javax.swing.JLabel();
        jTextFieldRechercher = new javax.swing.JTextField();
        jButtonMenuGeneral = new javax.swing.JButton();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Practicien");
        setResizable(false);

        jPanelPraticien.setLayout(null);

        jComboBoxChercher.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelPraticien.add(jComboBoxChercher);
        jComboBoxChercher.setBounds(330, 90, 190, 20);
        jPanelPraticien.add(jTextFieldCoefNotoriete);
        jTextFieldCoefNotoriete.setBounds(270, 300, 90, 20);

        jButtonSuivant.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonSuivant.setForeground(new java.awt.Color(0, 0, 153));
        jButtonSuivant.setText("Suivant");
        jPanelPraticien.add(jButtonSuivant);
        jButtonSuivant.setBounds(340, 410, 100, 23);

        jButtonPrecedent.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonPrecedent.setForeground(new java.awt.Color(0, 0, 153));
        jButtonPrecedent.setText("Précédent");
        jPanelPraticien.add(jButtonPrecedent);
        jButtonPrecedent.setBounds(140, 410, 110, 23);

        jButtonQuitter.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonQuitter.setForeground(new java.awt.Color(0, 0, 153));
        jButtonQuitter.setText("Quitter");
        jButtonQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitterActionPerformed(evt);
            }
        });
        jPanelPraticien.add(jButtonQuitter);
        jButtonQuitter.setBounds(530, 410, 100, 23);

        jButtonOk.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonOk.setForeground(new java.awt.Color(0, 0, 153));
        jButtonOk.setText("OK");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });
        jPanelPraticien.add(jButtonOk);
        jButtonOk.setBounds(530, 90, 80, 23);

        jSeparator.setBackground(new java.awt.Color(51, 51, 255));
        jSeparator.setForeground(new java.awt.Color(0, 0, 153));
        jPanelPraticien.add(jSeparator);
        jSeparator.setBounds(150, 120, 480, 10);

        jLabelNom.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNom.setForeground(new java.awt.Color(0, 0, 153));
        jLabelNom.setText("NOM");
        jPanelPraticien.add(jLabelNom);
        jLabelNom.setBounds(160, 140, 30, 14);

        jLabelPrenom.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPrenom.setForeground(new java.awt.Color(0, 0, 153));
        jLabelPrenom.setText("PRENOM");
        jPanelPraticien.add(jLabelPrenom);
        jLabelPrenom.setBounds(160, 180, 60, 14);

        jLabelPracticien.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabelPracticien.setForeground(new java.awt.Color(0, 0, 153));
        jLabelPracticien.setText("Praticien");
        jPanelPraticien.add(jLabelPracticien);
        jLabelPracticien.setBounds(300, 10, 230, 50);

        jLabelChercher.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelChercher.setForeground(new java.awt.Color(0, 0, 153));
        jLabelChercher.setText("Chercher");
        jPanelPraticien.add(jLabelChercher);
        jLabelChercher.setBounds(250, 90, 70, 14);

        jLabelAdresse.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAdresse.setForeground(new java.awt.Color(0, 0, 153));
        jLabelAdresse.setText("ADRESSE");
        jPanelPraticien.add(jLabelAdresse);
        jLabelAdresse.setBounds(160, 220, 70, 14);

        jLabelVille.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelVille.setForeground(new java.awt.Color(0, 0, 153));
        jLabelVille.setText("VILLE");
        jPanelPraticien.add(jLabelVille);
        jLabelVille.setBounds(160, 260, 40, 14);

        jLabelSecteur.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSecteur.setForeground(new java.awt.Color(0, 0, 153));
        jLabelSecteur.setText("COEF NOTORIETE");
        jPanelPraticien.add(jLabelSecteur);
        jLabelSecteur.setBounds(160, 300, 100, 14);

        jLabelLieuExercice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLieuExercice.setForeground(new java.awt.Color(0, 0, 153));
        jLabelLieuExercice.setText("LIEU D'EXERCICE");
        jPanelPraticien.add(jLabelLieuExercice);
        jLabelLieuExercice.setBounds(160, 340, 100, 14);

        jComboBoxLieuExercice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelPraticien.add(jComboBoxLieuExercice);
        jComboBoxLieuExercice.setBounds(270, 340, 240, 20);

        jTextFieldNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomActionPerformed(evt);
            }
        });
        jPanelPraticien.add(jTextFieldNom);
        jTextFieldNom.setBounds(270, 130, 250, 20);
        jPanelPraticien.add(jTextFieldPrenom);
        jTextFieldPrenom.setBounds(270, 170, 250, 20);

        jTextFieldAdresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAdresseActionPerformed(evt);
            }
        });
        jPanelPraticien.add(jTextFieldAdresse);
        jTextFieldAdresse.setBounds(270, 220, 250, 20);

        jTextFieldCodePostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodePostalActionPerformed(evt);
            }
        });
        jPanelPraticien.add(jTextFieldCodePostal);
        jTextFieldCodePostal.setBounds(270, 260, 50, 20);

        jTextFieldVille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVilleActionPerformed(evt);
            }
        });
        jPanelPraticien.add(jTextFieldVille);
        jTextFieldVille.setBounds(330, 260, 190, 20);

        jLabelRechercher.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelRechercher.setForeground(new java.awt.Color(0, 0, 153));
        jLabelRechercher.setText("Rechercher");
        jPanelPraticien.add(jLabelRechercher);
        jLabelRechercher.setBounds(250, 60, 70, 14);

        jTextFieldRechercher.setText("Nom Prénom");
        jPanelPraticien.add(jTextFieldRechercher);
        jTextFieldRechercher.setBounds(330, 60, 190, 20);

        jButtonMenuGeneral.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonMenuGeneral.setForeground(new java.awt.Color(0, 0, 153));
        jButtonMenuGeneral.setText("Menu général");
        jPanelPraticien.add(jButtonMenuGeneral);
        jButtonMenuGeneral.setBounds(50, 30, 130, 40);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gsb_background.png"))); // NOI18N
        jPanelPraticien.add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 750, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPraticien, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPraticien, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonQuitterActionPerformed

    private void jTextFieldCodePostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodePostalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodePostalActionPerformed

    private void jTextFieldAdresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAdresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAdresseActionPerformed

    private void jTextFieldVilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVilleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVilleActionPerformed

    private void jTextFieldNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VuePraticien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VuePraticien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VuePraticien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VuePraticien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VuePraticien().setVisible(true);
            }
        });
    }

    /**
     *
     * @return
     */
    public JButton getjButtonMenuGeneral() {
        return jButtonMenuGeneral;
    }
    
    /**
     *
     * @return
     */
    public JTextField getjTextFieldRechercher() {
        return jTextFieldRechercher;
    }

    /**
     *
     * @return
     */
    public JLabel getjLabelChercher() {
        return jLabelChercher;
    }

    /**
     *
     * @return
     */
    public JLabel getjLabelRechercher() {
        return jLabelRechercher;
    }
    
    /**
     *
     * @return
     */
    public JButton getjButtonQuitter() {
        return jButtonQuitter;
    }

    /**
     *
     * @return
     */
    public JButton getjButtonOk() {
        return jButtonOk;
    }

    /**
     *
     * @return
     */
    public JButton getjButtonPrecedent() {
        return jButtonPrecedent;
    }

    /**
     *
     * @return
     */
    public JButton getjButtonSuivant() {
        return jButtonSuivant;
    }

    /**
     *
     * @return
     */
    public JComboBox getjComboBoxChercher() {
        return jComboBoxChercher;
    }

    /**
     *
     * @return
     */
    public JComboBox getjComboBoxLieuExercice() {
        return jComboBoxLieuExercice;
    }

    /**
     *
     * @return
     */
    public JTextField getjTextFieldAdresse() {
        return jTextFieldAdresse;
    }

    /**
     *
     * @return
     */
    public JTextField getjTextFieldCodePostal() {
        return jTextFieldCodePostal;
    }

    /**
     *
     * @return
     */
    public JTextField getjTextFieldCoefNotoriete() {
        return jTextFieldCoefNotoriete;
    }

    /**
     *
     * @return
     */
    public JTextField getjTextFieldNom() {
        return jTextFieldNom;
    }

    /**
     *
     * @return
     */
    public JTextField getjTextFieldPrenom() {
        return jTextFieldPrenom;
    }

    /**
     *
     * @return
     */
    public JTextField getjTextFieldVille() {
        return jTextFieldVille;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMenuGeneral;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JButton jButtonPrecedent;
    private javax.swing.JButton jButtonQuitter;
    private javax.swing.JButton jButtonSuivant;
    private javax.swing.JComboBox jComboBoxChercher;
    private javax.swing.JComboBox jComboBoxLieuExercice;
    private javax.swing.JLabel jLabelAdresse;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelChercher;
    private javax.swing.JLabel jLabelLieuExercice;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelPracticien;
    private javax.swing.JLabel jLabelPrenom;
    private javax.swing.JLabel jLabelRechercher;
    private javax.swing.JLabel jLabelSecteur;
    private javax.swing.JLabel jLabelVille;
    private javax.swing.JPanel jPanelPraticien;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JTextField jTextFieldAdresse;
    private javax.swing.JTextField jTextFieldCodePostal;
    private javax.swing.JTextField jTextFieldCoefNotoriete;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPrenom;
    private javax.swing.JTextField jTextFieldRechercher;
    private javax.swing.JTextField jTextFieldVille;
    // End of variables declaration//GEN-END:variables
}
