/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vues;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author btssio
 */
public class VueRapportVisite extends javax.swing.JFrame {

    /**
     * Creates new form JFrameRapportVisite
     */
    public VueRapportVisite() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabelRapportVisite = new javax.swing.JLabel();
        jLabelNuméroRapport = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaBilan = new javax.swing.JTextArea();
        jTextFieldNumeroRapport = new javax.swing.JTextField();
        jLabelPraticien = new javax.swing.JLabel();
        jComboBoxPraticien = new javax.swing.JComboBox();
        jButtonDetailsPraticien = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabelMotifVisite = new javax.swing.JLabel();
        jTextFieldMotifVisite = new javax.swing.JTextField();
        jLabelBilan = new javax.swing.JLabel();
        jDateChooserDateRapport = new com.toedter.calendar.JDateChooser();
        jLabelOffreEchantillons = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableOffreEchantillons = new javax.swing.JTable();
        jButtonPrécédent = new javax.swing.JButton();
        jButtonSuivant = new javax.swing.JButton();
        jButtonNouveau = new javax.swing.JButton();
        jButtonFermer = new javax.swing.JButton();
        jButtonMenuGeneral = new javax.swing.JButton();
        jLabelBackground = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Rapport de visite");
        setResizable(false);

        jPanel1.setLayout(null);

        jLabelRapportVisite.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabelRapportVisite.setForeground(new java.awt.Color(0, 0, 153));
        jLabelRapportVisite.setText("Rapport de visite");
        jPanel1.add(jLabelRapportVisite);
        jLabelRapportVisite.setBounds(210, 0, 330, 44);

        jLabelNuméroRapport.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNuméroRapport.setForeground(new java.awt.Color(153, 153, 153));
        jLabelNuméroRapport.setText("Numéro rapport :");
        jPanel1.add(jLabelNuméroRapport);
        jLabelNuméroRapport.setBounds(130, 60, 120, 14);

        jTextAreaBilan.setColumns(20);
        jTextAreaBilan.setRows(5);
        jScrollPane3.setViewportView(jTextAreaBilan);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(300, 240, 440, 80);

        jTextFieldNumeroRapport.setEditable(false);
        jPanel1.add(jTextFieldNumeroRapport);
        jTextFieldNumeroRapport.setBounds(300, 60, 90, 20);

        jLabelPraticien.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPraticien.setForeground(new java.awt.Color(0, 0, 153));
        jLabelPraticien.setText("Praticien :");
        jPanel1.add(jLabelPraticien);
        jLabelPraticien.setBounds(130, 110, 90, 14);

        jComboBoxPraticien.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBoxPraticien);
        jComboBoxPraticien.setBounds(300, 110, 150, 20);

        jButtonDetailsPraticien.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonDetailsPraticien.setForeground(new java.awt.Color(0, 0, 153));
        jButtonDetailsPraticien.setText("Détails");
        jPanel1.add(jButtonDetailsPraticien);
        jButtonDetailsPraticien.setBounds(470, 110, 100, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Date rapport :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 160, 100, 14);

        jLabelMotifVisite.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMotifVisite.setForeground(new java.awt.Color(0, 0, 153));
        jLabelMotifVisite.setText("Motif visite :");
        jPanel1.add(jLabelMotifVisite);
        jLabelMotifVisite.setBounds(130, 210, 90, 14);
        jPanel1.add(jTextFieldMotifVisite);
        jTextFieldMotifVisite.setBounds(300, 210, 210, 20);

        jLabelBilan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelBilan.setForeground(new java.awt.Color(0, 0, 153));
        jLabelBilan.setText("Bilan");
        jPanel1.add(jLabelBilan);
        jLabelBilan.setBounds(130, 260, 70, 14);
        jPanel1.add(jDateChooserDateRapport);
        jDateChooserDateRapport.setBounds(300, 160, 120, 30);

        jLabelOffreEchantillons.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelOffreEchantillons.setForeground(new java.awt.Color(0, 0, 153));
        jLabelOffreEchantillons.setText("Offre d'échantillons :");
        jPanel1.add(jLabelOffreEchantillons);
        jLabelOffreEchantillons.setBounds(130, 320, 130, 14);

        jTableOffreEchantillons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Médicament", "Nb échantillon(s)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableOffreEchantillons);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(130, 340, 440, 90);

        jButtonPrécédent.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonPrécédent.setForeground(new java.awt.Color(0, 0, 153));
        jButtonPrécédent.setText("Précédent");
        jPanel1.add(jButtonPrécédent);
        jButtonPrécédent.setBounds(130, 440, 120, 23);

        jButtonSuivant.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonSuivant.setForeground(new java.awt.Color(0, 0, 153));
        jButtonSuivant.setText("Suivant");
        jPanel1.add(jButtonSuivant);
        jButtonSuivant.setBounds(270, 440, 100, 23);

        jButtonNouveau.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonNouveau.setForeground(new java.awt.Color(0, 0, 153));
        jButtonNouveau.setText("Nouveau");
        jPanel1.add(jButtonNouveau);
        jButtonNouveau.setBounds(390, 440, 110, 23);

        jButtonFermer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonFermer.setForeground(new java.awt.Color(0, 0, 153));
        jButtonFermer.setText("Fermer");
        jPanel1.add(jButtonFermer);
        jButtonFermer.setBounds(610, 440, 100, 23);

        jButtonMenuGeneral.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonMenuGeneral.setForeground(new java.awt.Color(0, 0, 153));
        jButtonMenuGeneral.setText("Menu général");
        jButtonMenuGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuGeneralActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMenuGeneral);
        jButtonMenuGeneral.setBounds(10, 10, 130, 40);

        jLabelBackground.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelBackground.setForeground(new java.awt.Color(0, 0, 153));
        jLabelBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\Benoit\\Documents\\NetBeansProjects\\GSB_Visiteurs\\GSB_Visiteurs\\images\\gsb_background.png")); // NOI18N
        jPanel1.add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 1070, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMenuGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuGeneralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMenuGeneralActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueRapportVisite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueRapportVisite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueRapportVisite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueRapportVisite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueRapportVisite().setVisible(true);
            }
        });
    }

    public JButton getjButtonDetailsPraticien() {
        return jButtonDetailsPraticien;
    }

    public JButton getjButtonFermer() {
        return jButtonFermer;
    }

    public JButton getjButtonNouveau() {
        return jButtonNouveau;
    }

    public JButton getjButtonPrecedent() {
        return jButtonPrécédent;
    }

    public JButton getjButtonSuivant() {
        return jButtonSuivant;
    }

    public JComboBox getjComboBoxPraticien() {
        return jComboBoxPraticien;
    }

    public JDateChooser getjDateChooserDateRapport() {
        return jDateChooserDateRapport;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public JTable getjTableOffreEchantillons() {
        return jTableOffreEchantillons;
    }

    public JTextArea getjTextAreaBilan() {
        return jTextAreaBilan;
    }

    public JTextField getjTextFieldMotifVisite() {
        return jTextFieldMotifVisite;
    }

    public JTextField getjTextFieldNumeroRapport() {
        return jTextFieldNumeroRapport;
    }

    public JButton getjButtonMenuGeneral() {
        return jButtonMenuGeneral;
    }

    public JButton getjButtonPrécédent() {
        return jButtonPrécédent;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetailsPraticien;
    private javax.swing.JButton jButtonFermer;
    private javax.swing.JButton jButtonMenuGeneral;
    private javax.swing.JButton jButtonNouveau;
    private javax.swing.JButton jButtonPrécédent;
    private javax.swing.JButton jButtonSuivant;
    private javax.swing.JComboBox jComboBoxPraticien;
    private com.toedter.calendar.JDateChooser jDateChooserDateRapport;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelBilan;
    private javax.swing.JLabel jLabelMotifVisite;
    private javax.swing.JLabel jLabelNuméroRapport;
    private javax.swing.JLabel jLabelOffreEchantillons;
    private javax.swing.JLabel jLabelPraticien;
    private javax.swing.JLabel jLabelRapportVisite;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableOffreEchantillons;
    private javax.swing.JTextArea jTextAreaBilan;
    private javax.swing.JTextField jTextFieldMotifVisite;
    private javax.swing.JTextField jTextFieldNumeroRapport;
    // End of variables declaration//GEN-END:variables
}
